version: '3.8'

services:
  web:
    build: .
    command: gunicorn taskmates.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=taskmates_user
      - POSTGRES_PASSWORD=taskmates_password
      - POSTGRES_DB=taskmates_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskmates_user -d taskmates_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  postgres_data:
